FROM ubuntu:20.04

LABEL maintainer="MamoruDS <mamoruds.io@gmail.com>"

ARG DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y \
    wget \
    python3 \
    python3-pip

RUN wget https://packages.microsoft.com/config/ubuntu/19.10/packages-microsoft-prod.deb -O packages-microsoft-prod.deb \
    && dpkg -i packages-microsoft-prod.deb

RUN apt update \
    && apt install -y apt-transport-https \
    && apt update \
    && apt install -y dotnet-sdk-3.1

RUN pip3 install jupyter \
    && mkdir -p /notebook \
    && dotnet tool install -g Microsoft.Quantum.IQSharp \
    && ~/.dotnet/tools/dotnet-iqsharp install

EXPOSE 8888

CMD jupyter notebook --ip=0.0.0.0 --allow-root --NotebookApp.token='' --NotebookApp.notebook_dir='/notebook' --no-browser
